travis:
  secure:
    BINSTAR_TOKEN: yUpJzWfrYtIVp4PFVtDHqVjMDMH3Qm1JO5ABlepFXchxiBJoYatYqTR0XtxjUjtxfawPxtl83tPff9JqFZgTQoYXS3FWaNK4cZasw9oqt85IBHl174wepIvsqjuhKiRQww2azHWatOPlEhe9IyvsF4L1na0dGv83G1uHxU9OPBxw7yJEvJp5Qx4kvsoxzNBkz+l/JsAfTS0dY5G0xgaypudUPO1/6nNys7PL48/SC5zx5aRM7kUTJBk1VsE9UfM2kWU34SYiRpHOucksRC38nPsxUZVJwvBW57Eez5Ka/GF2iZgUl7ogtWD3yQehJCp678l7Me/fIp4BYoaoq/HKOzGjkJ1cNNTPA0Ryz9PsIRY1gIMQnKuooS6XCtdTbhJRhl4xNjRS3ViKGz7s0qtYM0JMfCSTG49dU+Pk5WQY0hLshJiUw56QK+ZjtqurDzQFBeRVSJQRDfw15tcWn68QoHTM02NvDuzeV5vkefeR2v/qyFvz3BMJGZ+R/Atv66v6EsYT9pf8sICt9lyh0amrhr9oK3BPIC6bZ93EEcE/nPnqzIbfYw1SoYi411d57DnjyZp9TaoxTmDmh2fH5ZIMe4vNpLVZ272n/+HeuMIHrPnNkBjDPE+0J6qNnLHIGmbFcvfD3CYYwtyWsZrkrO3k7ScHYSd/OzoUAz3WFoowp+Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
