travis:
  secure:
    BINSTAR_TOKEN: HFTTRrVW6XEDrkmBahcYh8HqSJd6EgpXcm5yAN1kkoWlON0g3PiSgbswHpvduPCgkhuPeCyYMylcMstd7sDvS5YXgNI0jZ3Hqag8vlPekm+r1a5fX4JqHMu+uOuMsVWkSJgwa+GG3SDkcdGgHDue/4wVMnkt1dC3ULptRyJNH0rF+9feH0lc1FNhuQVv1S+6uqtr01rC3B4MZvnwxxRbewN8ULqDtP/Urc7eGQhn+r0R3R5ubpsTit79bIyvtY9VMiE8ydroUt4QTLxbxFky557aDfiDHllaYXlst+yxdRzIJduP8VXmZ+3T25qojzKgf2rrAJ6YpCrSxdIpUqea/wzHGXbAGevBsLsz4ZD6/LMUZ3uSRuIgBqrm3Esvnc4TyvCInYUJzzf//LpbEOhmU6qPjiDvDfBsr5nKAVwbUVZmu33wT7uOehUr5V4/FbMf5tzm15BcwniKx5pHat27C/0asLTkd7RHRPwk5WF3xgDhYoBC5xZkaf6PbwBZO2hQBWo6SU7JeJZ17llLvRItAzxfFJapBSv704h7Tldh/vVxvTGIbgHDMDIh7xUdYHJmviLdC4iZsxla/dLCfO17CX0NDbqx+tpaBZCcSAeF8cDfbz+Q1A2fx/SzfxppbI7/yE24tZLcpMPVq/YjMbbye0SqdT+GbOZnKYXqxJwHVoQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
